# Dialog Simulation Configuration

# Dialog Domain Settings
domain_config: sample_domains/movies/movie_domain.yaml
domain_kb_type: table
domain_kb_file_path: sample_domains/movies/moviekb.csv
domain_kb_file_type: csv

# User Simulator settings
usersim_class: sample_domains.movies.usersim.MovieUserSim
nlg_class: sample_domains.movies.usersim_nlg.UserSimNLGTemplate
starting_goal_path: sample_domains/movies/sample_starting_goals.yml
user_goal_type: template

# Dialog Agent settings
agent_class: sample_domains.movies.agent.MovieAgent

# Dialog Simulation settings
simulation_rounds: 3
max_turns: 8
first_speaker: usersim
reward: 10
simulation_output_path: data/simulated_dialogs/
save_history: True
save_location: "data/simulated_dialogs/"
save_type: json
