# Dialog Simulation Configuration

# Dialog Domain Settings
domain_config: sample_domains/restaurant/restaurant_domain.yaml
domain_kb_type: table
domain_kb_file_path: sample_domains/restaurant/restaurants_kb.json
domain_kb_file_type: json

# User Simulator settings
usersim_type: rules
usersim_class: sample_domains.restaurant.usersim.RestaurantUserSim
nlg_class: sample_domains.restaurant.usersim_nlg.UserSimNLGTemplate
starting_goal_path: sample_domains/restaurant/sample_starting_goals.yaml
user_goal_type: template

# Dialog Agent settings
agent_class: sample_domains.restaurant.agent.RestaurantAgent

# Dialog Simulation settings
simulation_rounds: 1
max_turns: 8
first_speaker: usersim
reward: 10
simulation_output_path: data/simulated_dialogs/
save_history: False
save_location: "data/simulated_dialogs/"
save_type: json
