# Dialog Simulation Configuration

# Dialog Domain Settings
domain_config: sample_domains/restaurant/restaurant_domain.yaml
domain_kb_type: table
domain_kb_file_path: sample_domains/restaurant/restaurants_kb.json
domain_kb_file_type: json

# User Simulator settings
usersim_type: rules
starting_goal_path: sample_domains/restaurant/sample_starting_goals.yaml
usersim_nlg_type: dict
usersim_nlg_path: sample_domains/restaurant/nlg_usersim_rules.yaml
user_goal_type: rules

# Dialog Agent settings
agent_type: rules
agent_nlg_type: dict
agent_nlg_path: sample_domains/restaurant/nlg_restaurant_agent.yaml
#agent_nlu_type: None

# Dialog Simulation settings
simulation_rounds: 1
max_turns: 8
first_speaker: usersim
reward: 10
simulation_output_path: data/simulated_dialogs/
save_history: True
save_location: "data/simulated_dialogs/"
save_type: json
