# Dialog Simulation Configuration

# Dialog Domain Settings
domain_config: sample_domains/restaurant/restaurant_domain.yaml
domain_kb_type: table
domain_kb_file_path: sample_domains/restaurant/restaurants_kb.json
domain_kb_file_type: json

# User Simulator location and settings
usersim_class: sample_domains.restaurant.usersim.RestaurantUserSim
nlg_class: sample_domains.restaurant.usersim_nlg.NLGModel
starting_goal_path: sample_domains/restaurant/sample_starting_goals.yaml
user_goal_type: template

# Dialog Agent location
agent_class: sample_domains.restaurant.agent.RestaurantAgent

# Dialog Simulation settings
first_speaker: usersim
corrupt_goal: .001
user_exit: .01
user_uncertainity: .05
max_turns: 8
simulation_rounds: 1
save_history: True
save_location: data/simulated_dialogs/
save_type: json
